Added README.Unix No longer using libtool.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -2,26 +2,32 @@ dnl Process this file with autoconf to produce a configure script.
 dnl
 dnl The basis for this file was generated by autoscan(1) [pere 1998-03-19]
 dnl
+
 AC_INIT(Simulator/Aircraft/aircraft.c)
+
+dnl Let the Win32 user specify if they want to build with the SGI
+dnl opengl.dll as opposed to the more standard openg32.dll
+AC_ARG_WITH(sgiopengl, [  --with-sgiopengl        Build against opengl.dll glu.dll and glut.dll])
 
 dnl Initialize the automake stuff
 AM_INIT_AUTOMAKE(FlightGear, 0.52)
 
 dnl Checks for programs.
-
 AC_PROG_MAKE_SET
 AC_PROG_CC
 AC_PROG_CXX
+AC_PROG_RANLIB
 AC_PROG_INSTALL
 AC_PROG_LN_S
-dnl Initialize libtool
-AM_PROG_LIBTOOL
 
-dnl Initialize maintainer mode (I'm not sure what this does)
+dnl Initialize libtool
+dnl AM_PROG_LIBTOOL
+
+dnl Initialize maintainer mode
 dnl AM_MAINTAINER_MODE
 
 dnl This is needed for AC_TRY_COMPILE later
-AC_ISC_POSIX
+dnl AC_ISC_POSIX
 
 dnl Check to see if this `configure' is being run in the `Cygwin32' environment
 dnl AM_CYGWIN32
@@ -48,7 +54,10 @@ AM_CONDITIONAL(ENABLE_AUDIO_SUPPORT, \
 	test -r /usr/include/soundcard.h \
 		-o -r /usr/include/linux/soundcard.h \
 		-o -r /usr/include/machine/soundcard.h \
+		-o -r /usr/include/audio.h \
 		-o "x$ac_cv_header_windows_h" = "xyes" )
+
+AM_CONDITIONAL(ENABLE_IRIX_AUDIO, test -r /usr/include/audio.h)
 
 AM_CONDITIONAL(ENABLE_WIN32_AUDIO, test "x$ac_cv_header_windows_h" = "xyes")
 
@@ -77,68 +86,87 @@ AC_CHECK_LIB(SM, SmcOpenConnection)
 AC_CHECK_LIB(Xt, XtMalloc)
 AC_CHECK_LIB(Xmu, XmuLookupStandardColormap)
 
-# dnl Solaris OpenGL pain
-# AC_CHECK_LIB(eprintf, __eprintf)
+dnl check for OpenGL related libraries
 
-AC_CHECK_LIB(GLcore, glNewList)
-if test "x$ac_cv_lib_GLcore_glNewList" = "xno" ; then
-    dnl if no GLcore, check for GL
-    AC_CHECK_LIB(GL, glNewList)
-    if test "x$ac_cv_lib_GL_glNewList" = "xno" ; then
-        dnl if no GL, check for MesaGL
-        AC_CHECK_LIB(MesaGL, glNewList)
+if test "x$ac_cv_header_windows_h" != "xyes" ; then
+    dnl Reasonable stuff non-windoze variants ... :-)
+
+    AC_CHECK_LIB(GLcore, glNewList)
+    if test "x$ac_cv_lib_GLcore_glNewList" = "xno" ; then
+	dnl if no GLcore, check for GL
+	AC_CHECK_LIB(GL, glNewList)
+	if test "x$ac_cv_lib_GL_glNewList" = "xno" ; then
+	    dnl if no GL, check for MesaGL
+	    AC_CHECK_LIB(MesaGL, glNewList)
+	fi
+    else
+	dnl if GLcore found, then also check for GL
+	AC_CHECK_LIB(GL, glXCreateContext)
     fi
+
+    dnl if using mesa, check for xmesa.h
+    if test "x$ac_cv_lib_MesaGL_glNewList" = "xyes" ; then
+	AC_CHECK_HEADER(GL/xmesa.h)
+	AM_CONDITIONAL(ENABLE_XMESA_FX, \
+		       test "x$ac_cv_header_GL_xmesa_h" = "xyes")
+    else
+        dnl force a failed check
+        AM_CONDITIONAL(ENABLE_XMESA_FX, test "no" = "yes")
+    fi
+
+    AC_CHECK_LIB(GLU, gluLookAt)
+    if test "x$ac_cv_lib_GLU_gluLookAt" = "xno" ; then
+	dnl if no GLU, check for MesaGLU
+	AC_CHECK_LIB(MesaGLU, gluLookAt)
+    fi
+
+    AC_CHECK_LIB(glut, glutGetModifiers)
 else
-    dnl if GLcore found, then also check for GL
-    AC_CHECK_LIB(GL, glXCreateContext)
-fi
+    dnl Win32 is a little wierd because it has to try to handle the various
+    dnl winbloze-isms.  We'll just do this manually for now.
 
-dnl if using mesa, check for xmesa.h
-if test "x$ac_cv_lib_MesaGL_glNewList" = "xyes" ; then
-    AC_CHECK_HEADER(GL/xmesa.h)
-    AM_CONDITIONAL(ENABLE_XMESA_FX, test "x$ac_cv_header_GL_xmesa_h" = "xyes")
-else
-    dnl force a failed check
-    AM_CONDITIONAL(ENABLE_XMESA_FX, test "no" = "yes")
-fi
-
-AC_CHECK_LIB(GLU, gluLookAt)
-if test "x$ac_cv_lib_GLU_gluLookAt" = "xno" ; then
-    dnl if no GLU, check for MesaGLU
-    AC_CHECK_LIB(MesaGLU, gluLookAt)
-fi
-
-AC_CHECK_LIB(glut, glutGetModifiers)
-	
-dnl Win32 is a little wierd because it has to try to handle the various
-dnl winbloze-isms.  We'll just do this manually for now.
-if test "x$ac_cv_header_windows_h" = "xyes" ; then
     echo Win32 specific hacks...
     AC_DEFINE(WIN32)
 
-    dnl Note, the double square brackets are required becuase single brackets
-    dnl seem to get stripped out
-    if [[ -f `pwd`/Win32/glut.dll ]]; then
-        echo "    found glut.dll, adding -lglut"
-        LIBS="$LIBS -lglut"
-    else
-        echo "    Cannot find glut.dll"
-        exit 1
+    dnl force a failed check since we will be building under windoze
+    AM_CONDITIONAL(ENABLE_XMESA_FX, test "no" = "yes")
+
+    if test "x$with_sgiopengl" = "xyes" ; then
+        echo "Building with glut.dll, glu.dll, and opengl.dll"
+	WIN32_GLUT=glut
+	WIN32_GLU=glu
+	WIN32_OPENGL=opengl
+    else 
+	echo "Building with glut32.dll, glu32.dll, and opengl32.dll"
+	WIN32_GLUT=glut32
+	WIN32_GLU=glu32
+	WIN32_OPENGL=opengl32
     fi
-    if [[ -f `pwd`/Win32/glu.dll ]]; then
-        echo "    found glu.dll"
+
+    if test -f `pwd`/Win32/${WIN32_GLUT}.dll; then
+	echo "    found ${WIN32_GLUT}.dll, adding -l${WIN32_GLUT}"
+	LIBS="$LIBS -l${WIN32_GLUT}"
     else
-        echo "    Can't find glu.dll, assuming it's someplace"
+	echo "    Cannot find ${WIN32_GLUT}.dll"
+	exit 1
     fi
-    echo "    adding -lglu"
-    LIBS="$LIBS -lglu"
-    if [[ -f `pwd`/Win32/opengl.dll ]]; then
-        echo "    found opengl.dll"
+
+    if test -f `pwd`/Win32/${WIN32_GLU}.dll; then
+	echo "    found ${WIN32_GLU}.dll"
     else
-        echo "    Can't find opengl.dll, assuming it's somplace"
+	echo "    Can't find ${WIN32_GLU}.dll, assuming it's someplace"
     fi
-    echo "    adding -lopengl"
-    LIBS="$LIBS -lopengl"
+    echo "    adding -l${WIN32_GLU}"
+    LIBS="$LIBS -l${WIN32_GLU}"
+
+    if test -f `pwd`/Win32/${WIN32_OPENGL}.dll; then
+	echo "    found ${WIN32_OPENGL}.dll"
+    else
+	echo "    Can't find ${WIN32_OPENGL}.dll, assuming it's somplace"
+    fi
+    echo "    adding -l${WIN32_OPENGL}"
+    LIBS="$LIBS -l${WIN32_OPENGL}"
+
     echo "    adding -luser32 -lgdi32"
     LIBS="$LIBS -luser32 -lgdi32"
     ac_cv_lib_glut_glutGetModifiers="yes"
